# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  lua_thread_config = debug
  main_test_config = debug
endif
ifeq ($(config),release)
  lua_thread_config = release
  main_test_config = release
endif

PROJECTS := lua_thread main_test

.PHONY: all clean help $(PROJECTS) Tests lua_thread

all: $(PROJECTS)

Tests: main_test

lua_thread: lua_thread

lua_thread:
ifneq (,$(lua_thread_config))
	@echo "==== Building lua_thread ($(lua_thread_config)) ===="
	@${MAKE} --no-print-directory -C lua_thread -f Makefile config=$(lua_thread_config)
endif

main_test: lua_thread
ifneq (,$(main_test_config))
	@echo "==== Building main_test ($(main_test_config)) ===="
	@${MAKE} --no-print-directory -C tests/main_test -f Makefile config=$(main_test_config)
endif

clean:
	@${MAKE} --no-print-directory -C lua_thread -f Makefile clean
	@${MAKE} --no-print-directory -C tests/main_test -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   lua_thread"
	@echo "   main_test"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"